### PR TITLE
Add build notes and pictures. 

### PR DESCRIPTION
**Pull request by JamesNewton**

### CODE REVIEW

**Comment by JamesNewton** [comment]
I thought I had created this pull request back in Sep... sorry if I didn't... I'm not a github expert. I was hoping your original description of the project would be easier for people to use with pictures, etc...

**Comment by jjsnyder619** [comment]
I hope I did that correctly. Not to familiar with Github. Please advise...

The pics are great! Looks like someone had lots of fun!

Also, have you had time to mess with an IR receiver on the bot? It would be great to repurpose an old remote to control the bot. I have a sketch that can get the IR codes for many brands of remote control units. From there, the remote control world can be one's proverbial oyster.

Peace

John

**Comment by JamesNewton** [comment]
Pictures were from Uyen's sessions at the library, used with her permission... Sadly, I haven't had the time to build one myself, although I did build a larger version from Parallax which did more or less the same things as part of a class I taught last summer. One of the kids in that class managed to get the IR working so you might search the parallax web site as they have code ready to go for their "Shield bot"

I'm honestly more interested in trying to use little DC motors with some sort of hand made position encoder to build cardboard robots for the battle league Uyen is pushing. Seems like that would bring in a lot of kids and further reduce the cost... but increase the complexity which actually increases the chances for learning. 

I've also been really intrigued by twisted string actuators. Google that up for a fun read. 

And if you have any interest in making larger things move, please let me know, I have H-bridges and stepper drivers available to educators in return for pictures and videos.

**Comment by JamesNewton** [comment]
oh, and yes, you did the merge correctly. I've updated the link to this from my page to point directly to your merged version rather than my fork
http://techref.massmind.org/techref/lessons.htm

**Pull request merged**
